[package]
name = "PageRank"
version = "0.1.0"
authors = ["ThomasHarris0147 <Thomasharris0147@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.0"
rand = "0.7"